### ISSUE TITLE
Jacobi Method

### ISSUE THREAD

**Issue by mwatwood-cu** [cucs-hpsc/hpsc-hw3#2]
Hi all,

I've been stuck on the Jacobi implementation for a little while.  

I feel like I am missing something simple to get this running. My main change to adjust for Jacobi was to modify the residual method in the inner for loop as follows:

```c
          PetscScalar laplacian = - u[j][i-1] - u[j][i+1] - u[j-1][i] - u[j+1][i];
          v[j][i] =(h2 - 1./4*(1-laplacian))-u[j][i];
```

Then use omega as 1 to only update from the iteration.

All help is appreciated, thanks!

**Comment by mwatwood-cu** [comment]
Resolved. Using the following gave convergence 
```c
          PetscScalar laplacian = - u[j][i-1] - u[j][i+1] - u[j-1][i] - u[j+1][i];
          v[j][i] =(h2 - 1./4*(h2-laplacian))-u[j][i];
```

**Comment by CamdenCU** [comment]
Nice workaround.  Also compare VecCopy/Swap to VecAXPY (from Table 1: PETSc Vector Operations in the [user manual](https://www.mcs.anl.gov/petsc/petsc-current/docs/manual.pdf)) to be able to remove the fifth `u` reference.
